development:
  adapter: postgresql
  encoding: unicode
  database: Squirrelicious_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: Squirrelicious_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: Squirrelicious_production
  pool: 5
